# NumPy Arrays: 
## Creating Arrays

In [2]:
import numpy as np
import matplotlib.pylab as plt
from numpy import random

In [3]:
list_1 = [1,2,3,4,5]
arr_1 = np.array(list_1,dtype=np.int8)
arr_1

array([1, 2, 3, 4, 5], dtype=int8)

In [4]:
m_list_1 = [[1,2,3],[4,5,6],[7,8,9]]
m_arr_1 = np.array(m_list_1)

In [5]:
m_arr_1.size

9

In [6]:
m_arr_1.dtype
# Data Types
# Boolean : np.bool_
# Char : np.byte
# Short : np.short
# Integer : np.short
# Long : np.int_
# Float : np.single & np.float32
# Double : np.double & np.float64
# np.int8 : -128 to 127
# np.int16 : -32768 to 32767
# np.int32 : -2147483648 to 2147483647
# np.int64 : -9223372036854775808 to 9223372036854775807

dtype('int32')

In [7]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [8]:
np.linspace(0,5,7)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.random.randint(10,50,5)


array([44, 47, 23, 29, 32])

In [12]:
np.random.randint(10,50, size=(2,3))

array([[18, 18, 34],
       [23, 40, 45]])

In [13]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

## Slicing and Indexes

In [14]:
print("np_m_arr_1\n", m_arr_1)
m_arr_1.shape
m_arr_1.item(0,2)

np.take(m_arr_1, [0,3,6])
np.put(m_arr_1, [0,3,6], [10, 10, 10])
m_arr_1

m_arr_1[:,1]
m_arr_1[::-1]

np_m_arr_1
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[10,  8,  9],
       [10,  5,  6],
       [10,  2,  3]])