# NumPy Arrays: 
## Creating Arrays

In [3]:
import numpy as np
import matplotlib.pylab as plt
from numpy import random

In [4]:
list_1 = [1,2,3,4,5]
arr_1 = np.array(list_1,dtype=np.int8)
arr_1

array([1, 2, 3, 4, 5], dtype=int8)

In [5]:
m_list_1 = [[1,2,3],[4,5,6],[7,8,9]]
m_arr_1 = np.array(m_list_1)

In [6]:
m_arr_1.size

9

In [7]:
m_arr_1.dtype
# Data Types
# Boolean : np.bool_
# Char : np.byte
# Short : np.short
# Integer : np.short
# Long : np.int_
# Float : np.single & np.float32
# Double : np.double & np.float64
# np.int8 : -128 to 127
# np.int16 : -32768 to 32767
# np.int32 : -2147483648 to 2147483647
# np.int64 : -9223372036854775808 to 9223372036854775807

dtype('int64')

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
np.linspace(0,5,7)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.random.randint(10,50,5)


array([27, 37, 40, 24, 11], dtype=int32)

In [13]:
np.random.randint(10,50, size=(2,3))

array([[33, 35, 19],
       [11, 35, 11]], dtype=int32)

In [14]:
np.random.randint?

Signature: np.random.randint(low, high=None, size=None, dtype=<class 'int'>)
Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-lik

## Slicing and Indexes

In [19]:
print("np_m_arr_1\n", m_arr_1)
m_arr_1[0,0] = 2
m_arr_1[0,1] = 1
m_arr_1

np_m_arr_1
 [[2 1 3]
 [4 5 6]
 [7 8 9]]


array([[2, 1, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
m_arr_1.shape
m_arr_1.item(0,2)

3

In [ ]:
np.take(m_arr_1, [0,3,6]) #

array([2, 4, 7])

In [ ]:
np.put(m_arr_1, [0,3,6], [10, 10, 10]) #
m_arr_1

array([[10,  1,  3],
       [10,  5,  6],
       [10,  8,  9]])

In [24]:
arr_1[:5:2]

array([1, 3, 5], dtype=int8)

In [26]:
m_arr_1[:,1]

array([1, 5, 8])

In [ ]:
m_arr_1[::-1] #

array([[10,  8,  9],
       [10,  5,  6],
       [10,  1,  3]])

In [29]:
evens = m_arr_1[m_arr_1%2==0]
evens

array([10, 10,  6, 10,  8])

In [31]:
m_arr_1[(m_arr_1 > 5) & (m_arr_1 < 9)]

array([6, 8])

In [32]:
np.unique(m_arr_1)

array([ 1,  3,  5,  6,  8,  9, 10])

# Reshaping Arrays

In [33]:
m_arr_1.reshape((1,9))

array([[10,  1,  3, 10,  5,  6, 10,  8,  9]])

In [ ]:
np.resize(m_arr_1, (2,5))

array([[10,  1,  3, 10,  5],
       [ 6, 10,  8,  9, 10]])

In [ ]:
m_arr_1.transpose()
# m_arr_1.swapaxes(0,1)

array([[10, 10, 10],
       [ 1,  5,  8],
       [ 3,  6,  9]])

In [40]:
m_arr_1.flatten('F')

array([10, 10, 10,  1,  5,  8,  3,  6,  9])

In [ ]:
m_arr_1.sort(axis=1) #row
m_arr_1

array([[ 1,  3, 10],
       [ 5,  6, 10],
       [ 8,  9, 10]])

# Stacking & Splitting

In [ ]:
ss_arr_1 = np.random.randint(10,size=(2,2))
print("ss_arr_1\n",ss_arr_1)
ss_arr_2 = np.random.randint(10,size=(2,2))
print("ss_arr_2\n",ss_arr_2)

np.vstack((ss_arr_1,ss_arr_2))
# np.hstack()

ss_arr_1
 [[9 2]
 [6 2]]
ss_arr_2
 [[6 6]
 [9 7]]


array([[9, 2],
       [6, 2],
       [6, 6],
       [9, 7]], dtype=int32)

In [49]:
ss_arr_3 = np.delete(ss_arr_1,1,0)
ss_arr_3

array([[9, 2]], dtype=int32)

In [ ]:
np.column_stack((ss_arr_3,ss_arr_3))
# np.row_stack()

array([[9, 2, 9, 2]], dtype=int32)

In [53]:
ss_arr_4 = np.random.randint(10,size=(2,10))
print("ss_arr_4\n", ss_arr_4)
np.hsplit(ss_arr_4,5)

ss_arr_4
 [[8 6 5 3 0 0 6 4 8 2]
 [2 8 9 6 3 8 5 6 4 5]]


[array([[8, 6],
        [2, 8]], dtype=int32),
 array([[5, 3],
        [9, 6]], dtype=int32),
 array([[0, 0],
        [3, 8]], dtype=int32),
 array([[6, 4],
        [5, 6]], dtype=int32),
 array([[8, 2],
        [4, 5]], dtype=int32)]

In [54]:
np.hsplit(ss_arr_4,(2,4))

[array([[8, 6],
        [2, 8]], dtype=int32),
 array([[5, 3],
        [9, 6]], dtype=int32),
 array([[0, 0, 6, 4, 8, 2],
        [3, 8, 5, 6, 4, 5]], dtype=int32)]

# Copying

In [56]:
cp_arr_1 = np.random.randint(10, size=(2,2))
cp_arr_2 = cp_arr_1
cp_arr_1[0,0] = 2
print("cp_arr_1\n", cp_arr_1)
print("cp_arr_2\n", cp_arr_2)

cp_arr_1
 [[2 8]
 [9 8]]
cp_arr_2
 [[2 8]
 [9 8]]


In [ ]:
cp_arr_3 = cp_arr_1.view() # shares memory
cp_arr_3.flatten("F")

array([2, 9, 8, 8], dtype=int32)

In [61]:
print("cp_arr_1\n", cp_arr_1)

cp_arr_1
 [[2 8]
 [9 8]]


In [ ]:
cp_arr_4 = cp_arr_1.copy() # new independent array

# Basic Math