# NumPy Arrays: 
## Creating Arrays

In [1]:
import numpy as np
import matplotlib.pylab as plt
from numpy import random

In [2]:
list_1 = [1,2,3,4,5]
arr_1 = np.array(list_1,dtype=np.int8)
arr_1

array([1, 2, 3, 4, 5], dtype=int8)

In [3]:
m_list_1 = [[1,2,3],[4,5,6],[7,8,9]]
m_arr_1 = np.array(m_list_1)

In [4]:
m_arr_1.size

9

In [5]:
m_arr_1.dtype
# Data Types
# Boolean : np.bool_
# Char : np.byte
# Short : np.short
# Integer : np.short
# Long : np.int_
# Float : np.single & np.float32
# Double : np.double & np.float64
# np.int8 : -128 to 127
# np.int16 : -32768 to 32767
# np.int32 : -2147483648 to 2147483647
# np.int64 : -9223372036854775808 to 9223372036854775807

dtype('int64')

In [6]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [7]:
np.linspace(0,5,7)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [8]:
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.random.randint(10,50,5)


array([18, 38, 29, 21, 41], dtype=int32)

In [11]:
np.random.randint(10,50, size=(2,3))

array([[41, 36, 21],
       [29, 43, 37]], dtype=int32)

In [12]:
np.random.randint?

Signature: np.random.randint(low, high=None, size=None, dtype=<class 'int'>)
Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-lik

## Slicing and Indexes

In [13]:
print("np_m_arr_1\n", m_arr_1)
m_arr_1[0,0] = 2
m_arr_1[0,1] = 1
m_arr_1

np_m_arr_1
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 1, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
m_arr_1.shape
m_arr_1.item(0,2)

3

In [15]:
np.take(m_arr_1, [0,3,6]) #

array([2, 4, 7])

In [16]:
np.put(m_arr_1, [0,3,6], [10, 10, 10]) #
m_arr_1

array([[10,  1,  3],
       [10,  5,  6],
       [10,  8,  9]])

In [17]:
arr_1[:5:2]

array([1, 3, 5], dtype=int8)

In [18]:
m_arr_1[:,1]

array([1, 5, 8])

In [19]:
m_arr_1[::-1] #

array([[10,  8,  9],
       [10,  5,  6],
       [10,  1,  3]])

In [20]:
evens = m_arr_1[m_arr_1%2==0]
evens

array([10, 10,  6, 10,  8])

In [21]:
m_arr_1[(m_arr_1 > 5) & (m_arr_1 < 9)]

array([6, 8])

In [22]:
np.unique(m_arr_1)

array([ 1,  3,  5,  6,  8,  9, 10])

# Reshaping Arrays

In [23]:
m_arr_1.reshape((1,9))

array([[10,  1,  3, 10,  5,  6, 10,  8,  9]])

In [24]:
np.resize(m_arr_1, (2,5))

array([[10,  1,  3, 10,  5],
       [ 6, 10,  8,  9, 10]])

In [25]:
m_arr_1.transpose()
# m_arr_1.swapaxes(0,1)

array([[10, 10, 10],
       [ 1,  5,  8],
       [ 3,  6,  9]])

In [26]:
m_arr_1.flatten('F')

array([10, 10, 10,  1,  5,  8,  3,  6,  9])

In [27]:
m_arr_1.sort(axis=1) #row
m_arr_1

array([[ 1,  3, 10],
       [ 5,  6, 10],
       [ 8,  9, 10]])

# Stacking & Splitting

In [28]:
ss_arr_1 = np.random.randint(10,size=(2,2))
print("ss_arr_1\n",ss_arr_1)
ss_arr_2 = np.random.randint(10,size=(2,2))
print("ss_arr_2\n",ss_arr_2)

np.vstack((ss_arr_1,ss_arr_2))
# np.hstack()

ss_arr_1
 [[0 6]
 [8 6]]
ss_arr_2
 [[9 4]
 [6 9]]


array([[0, 6],
       [8, 6],
       [9, 4],
       [6, 9]], dtype=int32)

In [29]:
ss_arr_3 = np.delete(ss_arr_1,1,0)
ss_arr_3

array([[0, 6]], dtype=int32)

In [30]:
np.column_stack((ss_arr_3,ss_arr_3))
# np.row_stack()

array([[0, 6, 0, 6]], dtype=int32)

In [31]:
ss_arr_4 = np.random.randint(10,size=(2,10))
print("ss_arr_4\n", ss_arr_4)
np.hsplit(ss_arr_4,5)

ss_arr_4
 [[0 8 8 5 9 3 5 4 3 2]
 [6 9 7 5 7 2 1 1 8 5]]


[array([[0, 8],
        [6, 9]], dtype=int32),
 array([[8, 5],
        [7, 5]], dtype=int32),
 array([[9, 3],
        [7, 2]], dtype=int32),
 array([[5, 4],
        [1, 1]], dtype=int32),
 array([[3, 2],
        [8, 5]], dtype=int32)]

In [32]:
np.hsplit(ss_arr_4,(2,4))

[array([[0, 8],
        [6, 9]], dtype=int32),
 array([[8, 5],
        [7, 5]], dtype=int32),
 array([[9, 3, 5, 4, 3, 2],
        [7, 2, 1, 1, 8, 5]], dtype=int32)]

# Copying

In [33]:
cp_arr_1 = np.random.randint(10, size=(2,2))
cp_arr_2 = cp_arr_1
cp_arr_1[0,0] = 2
print("cp_arr_1\n", cp_arr_1)
print("cp_arr_2\n", cp_arr_2)

cp_arr_1
 [[2 9]
 [2 6]]
cp_arr_2
 [[2 9]
 [2 6]]


In [34]:
cp_arr_3 = cp_arr_1.view() # shares memory
cp_arr_3.flatten("F")

array([2, 2, 9, 6], dtype=int32)

In [35]:
print("cp_arr_1\n", cp_arr_1)

cp_arr_1
 [[2 9]
 [2 6]]


In [36]:
cp_arr_4 = cp_arr_1.copy() # new independent array

# Basic Math

In [37]:
arr_3 = np.array([1,2,3,4])
arr_4 = np.array([2,4,6,8])
arr_3 / arr_4

array([0.5, 0.5, 0.5, 0.5])

In [42]:
arr_5 = random.randint(100, size=(4))
arr_5

array([88, 43, 23, 46], dtype=int32)

In [40]:
arr_6 = random.randint(100, size=(2,3))
arr_6

array([[58, 18, 75],
       [ 1, 49, 41]], dtype=int32)

In [43]:
random.rand(4)

array([0.94639928, 0.94175751, 0.42635493, 0.05142724])

In [46]:
random.choice(arr_3)

np.int64(2)

In [47]:
arr_3.sum()

np.int64(10)

In [49]:
arr_6.sum(axis=0)

array([ 59,  67, 116])

In [50]:
arr_6.cumsum(axis=1)

array([[ 58,  76, 151],
       [  1,  50,  91]])

In [ ]:
arr_6.min() # max()

np.int32(1)

In [ ]:
np.add(arr_3,arr_4) # subtract,multiple,divide

array([ 3,  6,  9, 12])

In [53]:
arr_7 = np.array([[1,2],[3,4]])
arr_8 = np.array([[2,4],[6,9]])
np.remainder(arr_8,arr_7)

array([[0, 0],
       [0, 1]])

In [ ]:
np.sqrt(arr_3) #cbrt

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [55]:
np.absolute([-1,-2])

array([1, 2])

In [57]:
np.exp(arr_3)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [59]:
np.log2(arr_3)

array([0.       , 1.       , 1.5849625, 2.       ])

In [ ]:
np.gcd.reduce([9,12,15]) #lcm

np.int64(3)

In [61]:
np.floor([1.2,2.5]) #ceil

array([1., 2.])

In [ ]:
sq_arr = np.arange(6)**2
sq_arr[arr_3] # retrieves elements at indices 1, 2, 3, 4

array([ 1,  4,  9, 16])

In [65]:
arr_9 = np.random.randint(10, size=(5,3))
print(arr_9)

[[3 4 1]
 [7 8 1]
 [2 7 8]
 [6 9 4]
 [5 9 5]]


In [67]:
mc_index = arr_9.argmax(axis=0)
mc_index

array([1, 3, 2])

In [68]:
max_num = arr_9[mc_index]
max_num

array([[7, 8, 1],
       [6, 9, 4],
       [2, 7, 8]], dtype=int32)

# Reading from Files

In [69]:
import pandas as pd
from numpy import genfromtxt

ic_sales = pd.read_csv('icecreamsales.csv').to_numpy()
ic_sales

array([[ 37, 292],
       [ 40, 228],
       [ 49, 324],
       [ 61, 376],
       [ 72, 440],
       [ 79, 496],
       [ 83, 536],
       [ 81, 556],
       [ 75, 496],
       [ 64, 412],
       [ 53, 324],
       [ 40, 320]])

In [71]:
ic_sales_2 = genfromtxt('icecreamsales.csv', delimiter=',')
ic_sales_2 = [row[~np.isnan(row)] for row in ic_sales_2]
ic_sales_2

[array([], dtype=float64),
 array([ 37., 292.]),
 array([ 40., 228.]),
 array([ 49., 324.]),
 array([ 61., 376.]),
 array([ 72., 440.]),
 array([ 79., 496.]),
 array([ 83., 536.]),
 array([ 81., 556.]),
 array([ 75., 496.]),
 array([ 64., 412.]),
 array([ 53., 324.]),
 array([ 40., 320.])]

# Statistics Functions

In [ ]:
saar_1 = np.arange(1,6)
np.mean(saar_1) 
# median average std var
# nanmedian, nanmean, nanstd, nanvar => ignore nan

np.float64(3.0)

In [77]:
print("ic_sales\n", ic_sales)
np.percentile(ic_sales, 50, axis=0)

ic_sales
 [[ 37 292]
 [ 40 228]
 [ 49 324]
 [ 61 376]
 [ 72 440]
 [ 79 496]
 [ 83 536]
 [ 81 556]
 [ 75 496]
 [ 64 412]
 [ 53 324]
 [ 40 320]]


array([ 62.5, 394. ])

In [76]:
ic_sales[:,0]

array([37, 40, 49, 61, 72, 79, 83, 81, 75, 64, 53, 40])

In [ ]:
np.corrcoef(ic_sales[:,0], ic_sales[:,1]) # close to 1 => very high correlated

array([[1.        , 0.96181329],
       [0.96181329, 1.        ]])

In [ ]:
# Calculating Regression line
# Σ(x-x̅)*(y-ȳ) / Σ(x-x̅)2

In [81]:
temp_mean = np.mean(ic_sales[:,0])
sales_mean = np.mean(ic_sales[:,1])
numerator = np.sum((ic_sales[:,0] - temp_mean) * (ic_sales[:,1] - sales_mean))
denominator = np.sum(np.square(ic_sales[:,0] - temp_mean))
slope = numerator/denominator
y_i = sales_mean - slope * temp_mean
y_i

np.float64(35.56162100218779)

In [82]:
reg_arr = ic_sales[:,0] * slope + y_i
reg_arr

array([256.01208459, 273.8864465 , 327.50953224, 399.00697989,
       464.54630691, 506.25315137, 530.08563392, 518.16939265,
       482.42066882, 416.88134181, 351.34201479, 273.8864465 ])

# Trig Functions